@startuml

title __MANAGERS's Class Diagram__\n

  namespace uas.lntv.pacmangame {
    namespace Managers {
      class uas.lntv.pacmangame.Managers.Assets {
          + ALARM : AssetDescriptor<Sound>
          + BLUE_DEAD : AssetDescriptor<Texture>
          + COIN_GOLD : AssetDescriptor<Texture>
          + CONTROL : String
          + DEATH_PAC : AssetDescriptor<Texture>
          + DIAL_UP : AssetDescriptor<Sound>
          + DIE : AssetDescriptor<Sound>
          + DOT : AssetDescriptor<Sound>
          + GAME_MUSIC : AssetDescriptor<Music>
          + GAME_MUSIC_2 : AssetDescriptor<Music>
          + GAME_MUSIC_3 : AssetDescriptor<Music>
          + GAME_MUSIC_4 : AssetDescriptor<Music>
          + GHOST_1 : AssetDescriptor<Texture>
          + GHOST_2 : AssetDescriptor<Texture>
          + GHOST_3 : AssetDescriptor<Texture>
          + HUNTING_MUSIC : AssetDescriptor<Music>
          + ITEM_HUNTER : AssetDescriptor<Texture>
          + ITEM_LIFE : AssetDescriptor<Texture>
          + ITEM_SLO_MO : AssetDescriptor<Texture>
          + ITEM_TIME : AssetDescriptor<Texture>
          + JOYSTICK_KNOB : AssetDescriptor<Texture>
          + JOYSTICK_ZONE : AssetDescriptor<Texture>
          + KILL : AssetDescriptor<Sound>
          + LIFE_UP : AssetDescriptor<Sound>
          + LOADING : AssetDescriptor<Texture>
          + MAP_1 : String
          + MAP_2 : String
          + MAP_3 : String
          + MAP_4 : String
          + MAP_5 : String
          + MENU_MAP : String
          + MENU_MUSIC : AssetDescriptor<Music>
          + PAC_MAN : AssetDescriptor<Texture>
          + PAUSE : String
          + POWER_UP : AssetDescriptor<Sound>
          + SCORE_MAP : String
          + SCORE_MUSIC : AssetDescriptor<Music>
          + SETTINGS_MAP : String
          + SETTINGS_MUSIC : AssetDescriptor<Music>
          + SLO_MO : AssetDescriptor<Sound>
          + SPLASH : String
          + SUPER_PAC : AssetDescriptor<Texture>
          + TILES : AssetDescriptor<Texture>
          + TIME : AssetDescriptor<Sound>
          + WHITE_DEAD : AssetDescriptor<Texture>
          + manager : AssetManager
          + dispose()
          + load()
          + loadSetup()
      }
    }
  }
  

  namespace uas.lntv.pacmangame {
    namespace Managers {
      class uas.lntv.pacmangame.Managers.PrefManager {
          {static} - causeOfDeath : ArrayList<String>
          {static} - highScores : ArrayList<Integer>
          {static} - init : boolean
          {static} - joystick : boolean
          {static} - level : ArrayList<Integer>
          {static} - musicOn : boolean
          {static} - name : String
          {static} - nameSet : boolean
          {static} - names : ArrayList<String>
          {static} - prefs : Preferences
          {static} - sfxOn : boolean
          + PrefManager()
          + addScore()
          {static} + getCauseOfDeath()
          {static} + getHighScores()
          {static} + getLevel()
          {static} + getNames()
          {static} + isJoystick()
          {static} + isMusicOn()
          {static} + isSfxOn()
          {static} + loadPrefs()
          {static} + noNameSet()
          {static} + resetScores()
          {static} + savePrefs()
          {static} + setJoystick()
          {static} + setMusicOn()
          {static} + setName()
          {static} + setNameSet()
          {static} + setSfxOn()
          {static} - anonymous()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
